---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    #- include: tasks/sudoers.yml
    - include: tasks/lynis.yml
    - include: tasks/filesystem.yml
    - include: tasks/ca-certs.yml
    - include: tasks/debian_packages.yml
    - include: tasks/audit.yml
    - include: tasks/login_defs.yml
    - include: tasks/pam.yml
    - include: tasks/services.yml
    - include: tasks/sysctl.yml
    - include: tasks/services-accounting.yml
    - include: tasks/apparmor.yml
    - include: tasks/logging.yml
    - include: tasks/misc.yml
    - include: tasks/banners.yml
    - include: tasks/network.yml
    - include: tasks/entropy.yml
    #- include: tasks/aide.yml
    #- include: tasks/rkhunter.yml
    #- include: tasks/clamav.yml
    #- include: tasks/display_managers.yml

  handlers:
    - include: tasks/handlers.yml
