---
- name: Install sudo
  apt:
    name: sudo
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
- name: Set file permissions/ownership for sudoers
  file:
    path: /etc/{{ item }}
    mode: g-w,o-rwx
    owner: root
    group: root
  become: yes
  tags: permissions
  with_items:
    - sudoers.d
    - sudoers
