# https://packages.cisofy.com/community/#debian-ubuntu
- name: Install Lynis into Debian
  block:
  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      update_cache: yes
  - name: Add Lynis signing key
    apt_key:
      id: 84FAA9983B24AEF24D6C87F1FEBB7D1812576482
      url: https://packages.cisofy.com/keys/cisofy-software-public.key
      state: present
  - name: Add Lynis repository
    apt_repository:
      repo: deb https://packages.cisofy.com/community/lynis/deb/ stable main
      state: present
  - name: Install Lynis
    apt:
      name: lynis
      update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
  tags:
  - packages
  - lynis
- name: Install Lynis into CentOS
  block:
  - name: Add Lynis repository
    yum_repository:
      name: lynis
      description: CISOfy Software - Lynis package
      baseurl: https://packages.cisofy.com/community/lynis/rpm/
      gpgkey: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
      gpgcheck: yes
      priority: 2
      enabled: yes
  - name: Install Lynis
    yum:
      name: lynis
      update_cache: yes
  when: ansible_distribution == "CentOS"
  become: yes
  tags:
  - packages
  - lynis
- name: Configure Lynis
  tags:
  - configuration
  - lynis
  block:
  - name: Configure Lynis to skip certain SSH tests
    lineinfile:
      path: /etc/lynis/custom.prf
      regexp: '^skip-test=SSH-7408:port$'
      line: skip-test=SSH-7408:port
      create: yes
  - name: Configure Lynis to skip certain tests
    blockinfile:
      path: /etc/lynis/custom.prf
      marker: "# {mark} ANSIBLE MANAGED BLOCK - Skip RPM related tests"
      block: |
        skip-test=PKGS-7308
        skip-test=PKGS-7383
        skip-test=PKGS-7384
        skip-test=PKGS-7386
        skip-test=PKGS-7387
    when: ansible_os_family != "RedHat"
  become: yes
