---
- name: Create harden.conf sysctl settings file
  become: yes
  copy:
    src: "{{ playbook_dir }}/newconfs/sysctl.d/{{ item }}.conf.new"
    dest: /etc/sysctl.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0600
  with_items:
    - sysctl
    - network
  tags:
  - configuration
  - kernel
  - network
  notify: "Load sysctl settings"
