---
- name: Setup AIDE
  block:
    - name: Install AIDE package
      apt:
        name: aide
        update_cache: yes
    - name: Configure AIDE
      replace:
        path: /etc/aide/aide.conf
        regexp: '^({{ item.key }}\s+=\s)+.*$'
        replace: '\g<1>{{ item.value }}'
      with_dict:
        Checksums: sha256
    - name: Exclude /net
      copy:
        content: "!/net$\n"
        dest: /etc/aide/aide.conf.d/70_net
        owner: root
        group: root
        mode: '0644'
        force: no
    - name: Exclude /media
      copy:
        content: "!/media$\n"
        dest: /etc/aide/aide.conf.d/70_media
        owner: root
        group: root
        mode: '0644'
        force: no
    - name: Create /etc/aide/aide.conf.d/70_misc
      copy:
        src: "{{ playbook_dir }}/../newconfs/aide-debian.conf.new"
        dest: /etc/aide/aide.conf.d/70_misc
        owner: root
        group: root
        mode: 0600
    - name: Check aide.conf
      command: /usr/bin/aide --config-check --config=/etc/aide/aide.conf
    - name: Create aide.db
      command: /usr/sbin/aideinit --yes
      args:
        creates: /var/lib/aide/aide.db
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
