---
- name: Install auditing
  block:
  - name: Install necessary software
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - auditd
      - libcap-ng-utils
  - name: Copy rules
    copy:
      remote_src: yes
      src: /usr/share/doc/auditd/examples/rules/{{ item }}
      dest: /etc/audit/rules.d/{{ item }}
    with_items:
      - 10-base-config.rules
      - 11-loginuid.rules
      - 20-dont-audit.rules
      - 30-stig.rules.gz
      - 42-injection.rules
      - 43-module-load.rules
      - 99-finalize.rules
  - name: Modify 20-dont-audit.rules
    block:
    - name: Uncomment exclude CRYPTO_KEY_USER
      replace:
        path: /etc/audit/rules.d/20-dont-audit.rules
        regexp: "^#?(-a always,exclude -F msgtype=CRYPTO_KEY_USER)$"
        replace: '\1'
    - name: Exclude CRYPTO_SESSION message type
      lineinfile:
        path: /etc/audit/rules.d/20-dont-audit.rules
        line: '-a always,exclude -F msgtype=CRYPTO_SESSION'
  - name: Unzip stig.rules
    command: /bin/gunzip -f /etc/audit/rules.d/30-stig.rules.gz
  - name: Disable noisy STIG rules
    replace:
      path: /etc/audit/rules.d/30-stig.rules
      regexp: "^(-.+-F key={{ item }})$"
      replace: '#\1'
    with_items:
      - perm_mod
      - delete
  - name: Create 31-privileged.rules
    block:
    - name: Create temp dir
      tempfile:
        state: directory
        suffix: temp
      register: tempdir_1
    - name: Copy Makefile
      copy:
        src: "{{ playbook_dir }}/../Makefile"
        dest: "{{ tempdir_1.path }}/"
        mode: 0600
    - name: Generate 31-privileged.rules
      make:
        chdir: "{{ tempdir_1.path }}"
        target: /etc/audit/rules.d/31-privileged.rules
    - name: Remove temp dir
      file:
        path: "{{ tempdir_1.path }}"
        state: absent
      when: tempdir_1.path is defined
  - name: Remove unnecessary file
    file:
      state: absent
      path: /etc/audit/rules.d/audit.rules
  - name: Create few custom rules
    assemble:
      remote_src: no
      src: "{{ playbook_dir }}/../newconfs/rules.d"
      dest: /etc/audit/rules.d/40-local.rules
  - name: Load the rules
    command: augenrules --load
  become: yes
  when: ( ansible_distribution == "Debian" and ansible_lsb.id != "Raspbian" ) or ansible_distribution == "Kali GNU/Linux"
