---
- name: Install security software
  block:
    - name: Install security software
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - debsums
        - bootlogd
        - tiger
        - iptables-persistent
        - libpam-passwdqc
        #- libpam-tmpdir
        - debsecan
        - autolog
        - rkhunter
        - chkrootkit
        - needrestart
        - arpwatch
        - clamav
        - usbguard
        - unattended-upgrades
    - include: aide.yml
    - name: Symlink /usr/lib/tiger/systems/Linux/5 -> 4
      file:
        src: /usr/lib/tiger/systems/Linux/4
        dest: /usr/lib/tiger/systems/Linux/5
        state: link
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
