---
- name: Install security software
  block:
    - name: Install security software
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - debsums
        - bootlogd
        - tiger
        - iptables-persistent
        - libpam-passwdqc
        #- libpam-tmpdir
        - debsecan
        - autolog
        - rkhunter
        - chkrootkit
        - needrestart
        - arpwatch
        - clamav
        - usbguard
        - unattended-upgrades
        - checksecurity
      tags:
      - packages
    - include: aide.yml
    - name: Symlink /usr/lib/tiger/systems/Linux/5 -> 4
      file:
        src: /usr/lib/tiger/systems/Linux/4
        dest: /usr/lib/tiger/systems/Linux/5
        state: link
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  become: yes
- name: Configure debsecan
  when: ansible_distribution == "Debian"
  become: yes
  debconf:
    name: debsecan
    question: debsecan/suite
    vtype: select
    value: "{{ ansible_distribution_release }}"
- name: Enable weekly debsums run
  replace:
    path: /etc/default/debsums
    regexp: '^(CRON_CHECK=).*'
    replace: '\g<1>weekly'
  become: yes
  when: ansible_distribution == "Debian"
- name: Create /etc/chkrootkit.ignore
  become: yes
  when: ansible_distribution == "Debian"
  copy:
    dest: /etc/chkrootkit.ignore
    owner: root
    group: root
    mode: '0400'
    content: |
      ^-e The following suspicious files and directories were found:$
      ^$
      ^ ?/usr/lib/debug/\.build-id$
      ^ ?/usr/lib/libreoffice/share/\.registry$
      ^ ?/usr/lib/ruby/vendor_ruby/rubygems/ssl_certs/\.document$
      ^ ?/usr/lib/pypy/lib_pypy/ctypes_config_cache/\.empty$
      ^eth[0-9]+: PACKET SNIFFER\(/usr/sbin/dhcpcd\[[0-9]+\](, /usr/sbin/collectd\[[0-9]+\])?\)$
- name: Configure /etc/cron.daily/chkrootkit to use chkrootkit.ignore
  replace:
    path: /etc/cron.daily/chkrootkit
    regexp: '^(IGNORE_FILE=).*'
    replace: '\g<1>/etc/chkrootkit.ignore'
  become: yes
  when: ansible_distribution == "Debian"
- name: Enable daily chkrootkit run
  replace:
    path: /etc/chkrootkit.conf
    regexp: '^(RUN_DAILY=).*'
    replace: '\g<1>"true"'
  become: yes
  when: ansible_distribution == "Debian"
