---
# https://github.com/canonical/lightdm#configuration
- name: Configure LightDM
  block:
  - name: Disable VNC in LightDM
    ini_file:
      path: /etc/lightdm/lightdm.conf
      section: VNCServer
      option: enabled
      value: "false"
  - name: Hide user list in LightDM
    ini_file:
      path: /etc/lightdm/lightdm.conf
      section: Seat:*
      option: greeter-hide-users
      value: "true"
  - name: Disallow guest login in LightDM
    ini_file:
      path: /etc/lightdm/lightdm.conf
      section: Seat:*
      option: allow-guest
      value: "false"
  become: yes
