---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    #- include: sudoers.yml
    - include: lynis.yml
    - include: filesystem.yml
    - include: ca-certs.yml
    - include: debian_packages.yml
    - include: audit.yml
    - include: login_defs.yml
    - include: pam.yml
    - include: services.yml
    - include: sysctl.yml
    - include: services-accounting.yml
    - include: apparmor.yml
    - include: logging.yml
    - include: misc.yml
    - include: banners.yml
    - include: network.yml
    - include: entropy.yml
    #- include: aide.yml
    #- include: rkhunter.yml
    #- include: clamav.yml
    #- include: display_managers.yml

  handlers:
    - name: Run update-ca-certificates
      become: yes
      when: ansible_os_family != "RedHat"
      command: /usr/sbin/update-ca-certificates --verbose --fresh
      tags:
      - configuration
      - pki
    - name: Load sysctl settings
      become: yes
      command: /sbin/sysctl -p /etc/sysctl.d/sysctl.conf /etc/sysctl.d/network.conf
      tags: kernel
      register: result
      failed_when:
        - result.failed
        - "result.stderr != 'sysctl: cannot stat /proc/sys/sys/kernel/modify_ldt: No such file or directory'"
    - name: Create rkhunter.dat
      command: /usr/bin/rkhunter --propupd
      become: yes
      tags: rkhunter
    # This takes a long time so we do it async
    - name: Create aide.db
      command: /usr/sbin/aideinit --yes --force
      tags: aide
      become: yes
      async: 3600
      poll: 0
      when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
    - name: Run pam-auth-update
      command: /usr/sbin/pam-auth-update --package
      become: yes
      tags:
      - pam
      - configuration
      when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
