---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    #- include: sudoers.yml
    - include: lynis.yml
    - include: filesystem.yml
    - include: ca-certs.yml
    - include: debian_packages.yml
    - include: audit.yml
    - include: login_defs.yml
    - include: pam.yml
    - include: services.yml
    - include: sysctl.yml
    - include: sysstat.yml
    - include: apparmor.yml
    - include: logging.yml
    - include: misc.yml
    - include: banners.yml
    - include: network.yml
    - include: entropy.yml
    #- include: aide.yml
    #- include: rkhunter.yml
    #- include: clamav.yml
    #- include: display_managers.yml
