---
- name: Configure shadow password suite (common)
  become: yes
  replace:
    path: /etc/login.defs
    regexp: '^(# ?)?({{ item.key }}\s+)[^\s]+$'
    replace: '\g<2>{{ item.value }}'
    validate: '/bin/grep "^{{ item.key }}\s\+{{ item.value }}$" %s'
  with_dict: "{{ defs_common }}"
  vars:
    defs_common:
      LOG_OK_LOGINS: "yes"
      UMASK: "077"
      SULOG_FILE: "/var/log/sulog"
      PASS_MAX_DAYS: 365
      PASS_MIN_DAYS: 7
      PASS_WARN_AGE: 30
      SHA_CRYPT_MIN_ROUNDS: 500000
      ENCRYPT_METHOD: "SHA512"
      CHFN_RESTRICT: "rwh"
      DEFAULT_HOME: "no"
      FAIL_DELAY: "{{ fail_delay }}"
      CREATE_HOME: "yes"
- name: Install glibc package (Slackware)
  when: ansible_distribution == "Slackware"
  become: yes
  command: slackpkg -batch=on -default_answer=y install glibc
- name: Limit the list of terminals from which root can log in (securetty)
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/securetty.new"
    dest: /etc/securetty
- name: Create /etc/profile.d/tmout.sh
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/profile.d/tmout.sh.new"
    dest: /etc/profile.d/tmout.sh
    owner: root
    group: root
    mode: '0755'
- name: Warn users about expiring password
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/expiry.sh.new"
    dest: /etc/profile.d/expiry.sh
    owner: root
    group: root
    mode: '0755'
- name: getent passwd
  getent:
    database: passwd
- name: Create /etc/ftpusers
  become: yes
  template:
    src: "{{ playbook_dir }}/templates/ftpusers.j2"
    dest: /etc/ftpusers
- include: login_defs-slackware.yml
  when: ansible_distribution == "Slackware"
- name: Verify integrity of group files
  become: yes
  command: grpck -r
- name: Remove pi from adm group (Debian)
  when: ansible_lsb.id == "Raspbian"
  become: yes
  command: gpasswd -d pi adm
  register: result
  failed_when:
    - result.failed == true
    - '"is not a member of" not in result.stderr'
- name: Inactive password lock
  block:
  - name: Set the number of days after a password expires until the account is permanently disabled (inactive)
    command: useradd -D -f 30
  - name: Same as above for existing users
    command: chage --inactive 30 {{ item.key }}
    when: item.value[1] | int >= 1000
    with_dict: "{{ getent_passwd }}"
    ignore_errors: yes
  become: yes
