---
# https://www.debian.org/doc/manuals/securing-debian-manual/ch04s11.en.html#id-1.5.14.10
- name: Configure shadow password suite (common)
  become: yes
  replace:
    path: /etc/login.defs
    regexp: '^(# ?)?({{ item.key }}\s+)[^\s]+$'
    replace: '\g<2>{{ item.value }}'
    validate: '/bin/grep "^{{ item.key }}\s\+{{ item.value }}$" %s'
  with_dict: "{{ defs_common }}"
  vars:
    defs_common:
      LOG_OK_LOGINS: "yes"
      UMASK: "077"
      SULOG_FILE: "/var/log/sulog"
      PASS_MAX_DAYS: 365
      PASS_MIN_DAYS: 7
      PASS_WARN_AGE: 30
      SHA_CRYPT_MIN_ROUNDS: 500000
      ENCRYPT_METHOD: "SHA512"
      CHFN_RESTRICT: "rwh"
      DEFAULT_HOME: "no"
      FAIL_DELAY: "{{ fail_delay }}"
      CREATE_HOME: "yes"
      HOME_MODE: "0700"
  tags: configuration
- name: Install glibc package (Slackware)
  when: ansible_distribution == "Slackware"
  become: yes
  command: slackpkg -batch=on -default_answer=y install glibc
  tags:
  - packages
# CIS Debian Linux 10 Benchmark v1.0.0 - 5.5 Ensure root login is restricted to system console
# https://www.debian.org/doc/manuals/securing-debian-manual/restrict-console-login.en.html
- name: Limit the list of terminals from which root can log in (securetty)
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/securetty.new"
    dest: /etc/securetty
  tags:
  - configuration
  - authorization
- name: Create /etc/profile.d/tmout.sh
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/profile.d/tmout.sh.new"
    dest: /etc/profile.d/tmout.sh
    owner: root
    group: root
    mode: '0755'
  tags: configuration
- name: Warn users about expiring password
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/profile.d/expiry.sh.new"
    dest: /etc/profile.d/expiry.sh
    owner: root
    group: root
    mode: '0755'
  tags: configuration
- name: getent passwd
  getent:
    database: passwd
# Slackware Linux Benchmark v1.1 - 7.3 Create ftpusers Files
# https://www.debian.org/doc/manuals/securing-debian-manual/ch04s11.en.html#id-1.5.14.12
- name: Create /etc/ftpusers
  become: yes
  template:
    src: "{{ playbook_dir }}/templates/ftpusers.j2"
    dest: /etc/ftpusers
    owner: root
    group: root
    mode: '0600'
  tags:
  - configuration
  - authorization
- include: login_defs-slackware.yml
  when: ansible_distribution == "Slackware"
# CIS Debian Linux 10 Benchmark v1.0.0 - 6.2.17 Ensure no duplicate GIDs exist
- name: Verify integrity of group files
  become: yes
  command: grpck -r
- name: Remove pi from adm group (Debian)
  when: ansible_lsb.id == "Raspbian"
  become: yes
  command: gpasswd -d pi adm
  register: result
  failed_when:
    - result.failed == true
    - '"is not a member of" not in result.stderr'
# CIS Debian Linux 10 Benchmark v1.0.0 - 5.4.1.4 Ensure inactive password lock is 30 days or less
- name: Inactive password lock
  block:
  # Debian's "useradd -D -f 30" fails with "cannot create new defaults file"
  - name: Set the number of days after a password expires until the account is permanently disabled (inactive)
    replace:
      path: /etc/default/useradd
      regexp: '^(# ?)?(INACTIVE=).*$'
      replace: '\g<2>30'
      validate: '/bin/grep "^INACTIVE=30$" %s'
    tags: configuration
  - name: Same as above for existing users
    command: chage --inactive 30 {{ item.key }}
    when: item.value[1] | int >= 1000 and item.value[1] | int <= 60000
    with_dict: "{{ getent_passwd }}"
    ignore_errors: yes
  become: yes
