---
- name: Disable core dumps
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux" or ansible_os_family == "RedHat" or ansible_distribution == "Slackware"
  become: yes
  pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: core
    value: 0
- name: Create /etc/modprobe.d/
  become: yes
  file:
    path: /etc/modprobe.d
    state: directory
- name: modprobe.d
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/modprobe.d/{{ item }}.conf.new"
    dest: /etc/modprobe.d/{{ item }}.conf
    owner: root
    group: root
    mode: 0600
  with_items:
    - CIS
    - bashbunny
    - firewire
    - usb-storage
- name: Make installpkg store md5sums (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  replace:
    path: /sbin/installpkg
    regexp: '^(MD5SUM)=[0-9]+$'
    replace: '\g<1>=1'
    validate: '/bin/grep "^MD5SUM=1$" %s'
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/selinux_users_and_administrators_guide/sect-security-enhanced_linux-working_with_selinux-disable_ptrace
- name: Disable ptrace() with SELinux
  become: yes
  when: ansible_os_family == "RedHat"
  seboolean:
    name: deny_ptrace
    state: yes
    persistent: yes
- name: Configure certbot to use 4096 bit keys
  block:
    - name: Check for /etc/letsencrypt
      stat:
        path: /etc/letsencrypt
      register: stat_result
    # https://certbot.eff.org/docs/using.html
    - name: Configure /etc/letsencrypt/cli.ini
      ini_file:
        path: /etc/letsencrypt/cli.ini
        section: null
        option: rsa-key-size
        value: 4096
        mode: '0600'
      when: stat_result.stat.exists == True
  become: yes
- name: Set verify_ap_req_nofail -> true in krb5.conf
  ini_file:
    path: /etc/krb5.conf
    section: libdefaults
    option: verify_ap_req_nofail
    value: "true"
  become: yes
# https://sourceforge.net/p/rkhunter/rkh_code/ci/master/tree/files/FAQ: "3.3) How can I automatically run Rootkit Hunter every day?"
- name: Add rkhunter cronjob
  cron:
    name: "Run rkhunter"
    minute: "30"
    hour: "5"
    job: "/usr/bin/test -x /usr/bin/rkhunter && /usr/bin/rkhunter --cronjob --update --rwo"
  become: yes
# These are packages that ship SUID/SGID binaries, pam.d configurations or similar stuff that provides unnecessary attack surface
# Slackware Linux Benchmark v1.1:
#   * SN.5 Evaluate Packages Associated With Startup Scripts
#   * 7.1 Disable rhosts Support
# system-hardening-10.2.txt: Misc Stuff -> Stuff to remove
- name: Remove stuff
  block:
    - name: Remove unneeded/unwanted packages (Slackware)
      slackpkg:
        name: '{{ item }}'
        state: absent
      with_items:
        - netkit-rsh
        - uucp
        - floppy
        - netatalk
        - slrn
        - yptools
    - name: Remove leftover files from removed packages
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /etc/pam.d/netatalk
        - /etc/rc.d/rc.atalk
  become: yes
  when: ansible_distribution == "Slackware"
