---
# System accounting
- name: Install sysstat
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  apt:
    name: sysstat
    update_cache: yes
  tags:
  - packages
  - services
  - accounting
- name: Enable system accounting (sysstat)
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  replace:
    path: /etc/default/sysstat
    regexp: '^ENABLED=.*$'
    replace: 'ENABLED="true"'
    validate: '/bin/grep "^ENABLED=\"true\"$" %s'
  tags:
  - services
  - accounting
  - configuration
- name: Install sysstat (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  slackpkg:
    name: sysstat
    state: present
  tags:
  - packages
  - services
  - accounting
- name: Enable rc.sysstat (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  file:
    path: /etc/rc.d/rc.sysstat
    owner: root
    group: root
    mode: 0700
  tags:
  - services
  - accounting
  - permissions
  - configuration
- name: Create sysstat cron jobs
  when: ansible_distribution == "Slackware"
  become: yes
  copy:
    src: "{{ playbook_dir }}/../newconfs/cron.d/sysstat.new"
    dest: /etc/cron.d/sysstat
  tags:
  - services
  - accounting
  - configuration
- name: Configure sysstat
  become: yes
  replace:
    path: /etc/sysstat/sysstat
    regexp: '^HISTORY=[0-9]+$'
    replace: 'HISTORY=99999'
    validate: '/bin/grep "^HISTORY=99999$" %s'
  tags:
  - services
  - accounting
  - configuration
# </System accounting>

# Process accounting
- name: Install acct
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  apt:
    name: acct
    update_cache: yes
  tags:
  - packages
  - services
  - accounting
- name: Enable acct
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Kali GNU/Linux"
  systemd:
    name: acct
    state: started
    enabled: yes
  tags:
  - services
  - accounting
  - configuration
- name: Install acct (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  slackpkg:
    name: acct
    state: present
  tags:
  - packages
  - services
  - accounting
- name: Create /var/log/pacct (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  copy:
    content: ""
    dest: /var/log/pacct
    force: no
    owner: root
    group: adm
    mode: '0640'
  tags:
  - services
  - accounting
- name: Create /etc/logrotate.d/pacct (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  copy:
    src: "{{ playbook_dir }}/../newconfs/logrotate.d/pacct.new"
    dest: /etc/logrotate.d/pacct
  tags:
  - services
  - accounting
- name: Start process accounting (Slackware)
  become: yes
  when: ansible_distribution == "Slackware"
  command: /sbin/accton /var/log/pacct
  tags:
  - services
  - accounting
# </Process accounting>
